# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(max_length=10)),
                ('run_date', models.DateTimeField(verbose_name='run date')),
            ],
        ),
    ]
