# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20170503_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='distance',
        ),
    ]
